# =============================================================================
# AgentCore Configuration - Faiston SGA Inventory
# =============================================================================
# Configuration for Bedrock AgentCore deployment.
# Module: Gestao de Ativos -> Gestao de Estoque
#
# Note: This file is overwritten by GitHub Actions during deployment.
# Local changes are for development reference only.
# =============================================================================

default_agent: faiston_sga_inventory_agents

agents:
  faiston_sga_inventory_agents:
    name: faiston_sga_inventory_agents
    entrypoint: main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: .
    aws:
      account: '377311924364'
      region: us-east-2
      execution_role_auto_create: true
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    memory:
      # Using STM_LTM for inventory context and historical patterns
      mode: STM_LTM
