// =============================================================================
// NEXO Observation Types - SGA Inventory Module
// =============================================================================
// Types for AI-generated observations during Smart Import flow.
// NEXO follows the "Observe → Learn → Act" pattern to analyze import data.
// =============================================================================

/**
 * Confidence factor contributing to overall score.
 */
export interface ConfidenceFactor {
  /** Factor identifier (e.g., 'data_completeness', 'format_consistency') */
  id: string;
  /** Human-readable label */
  label: string;
  /** Score for this factor (0-100) */
  score: number;
  /** Weight in overall calculation (0-1) */
  weight: number;
  /** Optional explanation */
  description?: string;
}

/**
 * Risk level assessment for the import.
 */
export type RiskLevel = 'low' | 'medium' | 'high';

/**
 * Confidence assessment structure.
 */
export interface ConfidenceAssessment {
  /** Overall confidence score (0-100) */
  overall: number;
  /** Individual factors contributing to score */
  factors: ConfidenceFactor[];
  /** Calculated risk level */
  risk_level: RiskLevel;
}

/**
 * NEXO's observations about the import data.
 */
export interface ObservationDetails {
  /** Patterns detected in the data */
  patterns: string[];
  /** Suggestions for improvement */
  suggestions: string[];
  /** Warnings about potential issues */
  warnings: string[];
}

/**
 * Learning insights for NEXO's memory.
 */
export interface LearningInsights {
  /** Category of learning (e.g., 'nf_import', 'bulk_import') */
  category: string;
  /** Key insights to remember */
  insights: string[];
}

/**
 * Complete NEXO observation response.
 * Generated by observation_agent.py using Gemini 3.0 Pro.
 */
export interface NexoObservation {
  /** Success indicator */
  success: boolean;
  /** Confidence assessment */
  confidence: ConfidenceAssessment;
  /** Detailed observations */
  observations: ObservationDetails;
  /** Natural language commentary in Portuguese */
  ai_commentary: string;
  /** Learning insights for NEXO memory */
  learn_from: LearningInsights;
  /** ISO timestamp of observation generation */
  generated_at: string;
  /** Processing time in milliseconds */
  processing_time_ms?: number;
}

/**
 * Request payload for generating observations.
 */
export interface GenerateObservationsRequest {
  /** The import preview data to analyze */
  preview: {
    source_type: string;
    items_count: number;
    total_value?: number;
    supplier_name?: string;
    nf_number?: string;
    items?: Array<{
      description: string;
      quantity: number;
      unit_value?: number;
      part_number?: string;
    }>;
    validation_warnings?: string[];
    hil_required?: boolean;
  };
  /** Optional context about the import */
  context?: {
    project_id?: string;
    location_id?: string;
    user_notes?: string;
  };
}

/**
 * Default observation for error/fallback scenarios.
 */
export const DEFAULT_NEXO_OBSERVATION: NexoObservation = {
  success: true,
  confidence: {
    overall: 75,
    factors: [
      { id: 'data_completeness', label: 'Completude dos dados', score: 75, weight: 0.3 },
      { id: 'format_consistency', label: 'Consistência do formato', score: 80, weight: 0.3 },
      { id: 'value_validation', label: 'Validação de valores', score: 70, weight: 0.4 },
    ],
    risk_level: 'low',
  },
  observations: {
    patterns: [],
    suggestions: [],
    warnings: [],
  },
  ai_commentary: 'Dados analisados com sucesso. Aguardando confirmação para prosseguir.',
  learn_from: {
    category: 'import_general',
    insights: [],
  },
  generated_at: new Date().toISOString(),
};

/**
 * Get risk level color class for UI.
 */
export function getRiskLevelColor(level: RiskLevel): string {
  switch (level) {
    case 'low':
      return 'text-[#00FAFB]'; // Faiston cyan
    case 'medium':
      return 'text-amber-400';
    case 'high':
      return 'text-[#FD5665]'; // Faiston coral
    default:
      return 'text-gray-400';
  }
}

/**
 * Get risk level label in Portuguese.
 */
export function getRiskLevelLabel(level: RiskLevel): string {
  switch (level) {
    case 'low':
      return 'Baixo';
    case 'medium':
      return 'Médio';
    case 'high':
      return 'Alto';
    default:
      return 'Desconhecido';
  }
}

/**
 * Get confidence level description.
 */
export function getConfidenceDescription(score: number): string {
  if (score >= 90) return 'Excelente';
  if (score >= 75) return 'Bom';
  if (score >= 60) return 'Moderado';
  if (score >= 40) return 'Baixo';
  return 'Muito baixo';
}
